In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.metrics import mean_absolute_error

In [2]:
class LA:
    def __init__(self):
        self.m=None
        self.b=None

    def fit(self,X_train,Y_train):

        num=0
        den=0

        for i in range(X_train.shape[0]):
            num += (X_train[i] - X_train.mean()) * (Y_train[i] - Y_train.mean())
            den += (X_train[i] - X_train.mean()) ** 2

        self.m=num/den
        self.b=Y_train.mean()-(self.m*X_train.mean())
        print(self.m)
        print(self.b)
        

    def predict(self,X_test):
        return self.m*X_test+self.b

In [3]:
df=pd.read_csv("Study_Hour.csv")

In [4]:
df.head(10)

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes


In [6]:
X = df["Hours"].values
Y = df["Scores"].values

# No null valus so we can train the model and check the result ,, lets make comparsion between sklearn linear regression and our LA class

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [9]:
X_train.shape


(20,)

In [10]:
Y_train.shape

(20,)

## Doing Linear regression testing 

In [12]:
l=LA()

#### one is slope and other is intercept

In [13]:
l.fit(X_train,Y_train)

9.682078154455699
2.82689235389973


In [15]:
l.predict(Y_test)

array([787.07522286, 293.28923699, 206.1505336 , 738.66483209,
       603.11573793])

In [86]:
y_pred=l.predict(X_test)
y_pred

array([[83.18814104],
       [27.03208774],
       [27.03208774],
       [69.63323162],
       [59.95115347]])

In [88]:
n=Y_test.shape
n

(5, 1)

## Doing sklearn linear regresion model testing 

In [18]:
from sklearn.linear_model import LinearRegression


### As X is 1d array but sklearn linear regression required 2d array converting X in 2d

In [20]:
X = df[["Hours"]]
Y = df[["Scores"]]

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [21]:
X_train.shape

(20, 1)

In [22]:
Y_train.shape

(20, 1)

In [23]:
model=LinearRegression()

In [24]:
l=model.fit(X_train,Y_train)


In [25]:
y_preds=l.predict(X_test)                    # → gives predictions of Y values

In [26]:
l.coef_  ## slope 

array([[9.68207815]])

In [27]:
l.intercept_    ## intercept b

array([2.82689235])

###  Lets make Evalution of this results mae,R2 etc

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [67]:
mae = mean_absolute_error(Y_test, y_preds)
mse = mean_squared_error(Y_test, y_preds)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_preds)

In [69]:
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 3.9207511902099244
Mean Squared Error (MSE): 18.943211722315272
Root Mean Squared Error (RMSE): 4.352380006653288
R² Score: 0.9678055545167994


In [95]:
n = len(X_test)   # number of test samples and check using X_test.shape
k = 1             # one independent variable

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - k - 1)
print("Adjusted R²:", adj_r2)


Adjusted R²: 0.9570740726890659


In [1]:
class MR:
    def __init__(self,learning_rate,epochs):
        self.learning_rate=0.01
        self.epochs=100
        self.m=none
        self.b=none

    def fit(self,m,b):
        pass



    def predict(self,X_test):
        pass


        